name: reviewdog
on: [pull_request]
jobs:
    eslint:
        name: runner / eslint
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - uses: bahmutov/npm-install@v1
            - name: eslint
              uses: reviewdog/action-eslint@v1
